/**
 * Runs the app's own sign-in code against a real importer container.
 *
 * Every other test here mocks the network, which proves the app behaves
 * consistently but not that the portal agrees with it. This one talks to a live
 * portal: same PKCE, same parameter names, same token parsing, same refresh
 * rotation. If the two sides ever disagree about a field name or a status code,
 * this is where it shows up.
 *
 * Skipped unless `LIVE_PORTAL_URL` and `LIVE_PORTAL_PASSWORD` are set, so it
 * never runs in CI. The browser hop is replaced by a scripted HTTP login,
 * because a system browser is the one thing a unit-test process cannot host —
 * that leg is covered on a device instead.
 */
import { refreshTokens, SESSION_ENDED } from '../api/appTokens';
import { signIn } from './appAuthFlow';

const BASE = String(process.env.LIVE_PORTAL_URL ?? '');
const PASSWORD = String(process.env.LIVE_PORTAL_PASSWORD ?? '');
const isConfigured = BASE.length > 0 && PASSWORD.length > 0;

const BASE64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/**
 * Encodes bytes as standard, padded base64.
 *
 * Stands in for what the native crypto module returns. Getting this wrong would
 * produce a challenge the portal rejects, which is precisely what this test is
 * here to notice.
 * @param bytes - The bytes to encode.
 * @returns The padded base64 string.
 */
function toBase64(bytes: Uint8Array): string {
  let encoded = '';
  for (let offset = 0; offset < bytes.length; offset += 3) {
    const remaining = bytes.length - offset;
    const word =
      (bytes[offset] << 16) |
      ((remaining > 1 ? bytes[offset + 1] : 0) << 8) |
      (remaining > 2 ? bytes[offset + 2] : 0);
    const chars = [
      BASE64[(word >> 18) & 63],
      BASE64[(word >> 12) & 63],
      remaining > 1 ? BASE64[(word >> 6) & 63] : '=',
      remaining > 2 ? BASE64[word & 63] : '=',
    ];
    encoded += chars.join('');
  }
  return encoded;
}

const mockBrowser = { redirectUrl: '' };

/**
 * Produces random bytes the way the native module would.
 * @param byteCount - How many bytes to produce.
 * @returns The generated bytes.
 */
function mockRandomBytes(byteCount: number): Uint8Array {
  return globalThis.crypto.getRandomValues(new Uint8Array(byteCount));
}

/**
 * Hashes a string with SHA-256 and returns standard base64.
 * @param data - The value to hash.
 * @returns The padded base64 digest.
 */
async function mockDigestBase64(data: string): Promise<string> {
  const input = new TextEncoder().encode(data);
  const hashed = await globalThis.crypto.subtle.digest('SHA-256', input);
  return toBase64(new Uint8Array(hashed));
}

jest.mock('expo-crypto', () => ({
  CryptoDigestAlgorithm: { SHA256: 'SHA-256' },
  CryptoEncoding: { BASE64: 'base64' },
  getRandomBytesAsync: (byteCount: number) => Promise.resolve(mockRandomBytes(byteCount)),
  digestStringAsync: (_algorithm: string, data: string) => mockDigestBase64(data),
}));

jest.mock('expo-device', () => ({ deviceName: 'Live test device' }));

jest.mock('expo-linking', () => ({
  parse: (url: string) => {
    const query = url.includes('?') ? url.slice(url.indexOf('?') + 1) : '';
    const queryParams: Record<string, string> = {};
    for (const [key, value] of new URLSearchParams(query)) {
      queryParams[key] = value;
    }
    return { queryParams };
  },
}));

jest.mock('expo-web-browser', () => ({
  WebBrowserResultType: { CANCEL: 'cancel', DISMISS: 'dismiss', LOCKED: 'locked' },
  openAuthSessionAsync: (url: string) => mockSignInThroughPortal(url),
}));

/**
 * Signs in to the portal over HTTP and follows the authorize redirect.
 *
 * This stands in for the system browser: it collects the portal's session
 * cookie the same way a browser would, then replays the authorize request the
 * app built, unchanged.
 * @param authorizeUrl - The authorization URL the app produced.
 * @returns A browser-shaped result carrying the redirect.
 */
async function mockSignInThroughPortal(
  authorizeUrl: string,
): Promise<{ type: string; url?: string }> {
  const login = await fetch(`${BASE}/auth/login`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ password: PASSWORD }),
  });
  if (!login.ok) {
    throw new Error(`Portal login failed (${String(login.status)}).`);
  }
  const cookie = (login.headers.get('set-cookie') ?? '').split(';')[0];
  const authorized = await fetch(authorizeUrl, { headers: { cookie }, redirect: 'manual' });
  const location = authorized.headers.get('location') ?? '';
  mockBrowser.redirectUrl = location;
  return location.startsWith('bankimporter://')
    ? { type: 'success', url: location }
    : { type: 'locked' };
}

const describeLive = isConfigured ? describe : describe.skip;

describeLive('app sign-in against a live portal', () => {
  it('completes the flow and returns a usable access token', async () => {
    const tokens = await signIn(BASE);

    expect(mockBrowser.redirectUrl.startsWith('bankimporter://auth?')).toBe(true);
    expect(tokens.accessToken.length).toBeGreaterThan(0);
    expect(tokens.refreshToken.length).toBeGreaterThan(0);
    expect(tokens.expiresAt).toBeGreaterThan(Date.now());

    const guarded = await fetch(`${BASE}/api/status`, {
      headers: { authorization: `Bearer ${tokens.accessToken}` },
    });
    expect(guarded.status).toBe(200);
  }, 60_000);

  it('rotates the refresh token and keeps the session usable', async () => {
    const first = await signIn(BASE);
    const second = await refreshTokens(BASE, first.refreshToken);

    expect(second.refreshToken).not.toBe(first.refreshToken);

    const guarded = await fetch(`${BASE}/api/status`, {
      headers: { authorization: `Bearer ${second.accessToken}` },
    });
    expect(guarded.status).toBe(200);
  }, 60_000);

  it('refuses a refresh token that has already been spent', async () => {
    const first = await signIn(BASE);
    await refreshTokens(BASE, first.refreshToken);

    await expect(refreshTokens(BASE, first.refreshToken)).rejects.toThrow(SESSION_ENDED);
  }, 60_000);
});
