/**
 * Runs the app's own sign-in code against a real importer container.
 *
 * Every other test here mocks the network, which proves the app behaves
 * consistently but not that the portal agrees with it. This one talks to a live
 * portal: same PKCE, same parameter names, same token parsing, same refresh
 * rotation. If the two sides ever disagree about a field name or a status code,
 * this is where it shows up.
 *
 * Skipped unless `LIVE_PORTAL_URL` and `LIVE_PORTAL_PASSWORD` are set, so it
 * never runs in CI. The browser hop is replaced by a scripted HTTP login,
 * because a system browser is the one thing a unit-test process cannot host —
 * that leg is covered on a device instead.
 */
import { refreshTokens, SESSION_ENDED } from '../api/appTokens';
import { signIn } from './appAuthFlow';

const BASE = String(process.env.LIVE_PORTAL_URL ?? '');
const PASSWORD = String(process.env.LIVE_PORTAL_PASSWORD ?? '');
const isConfigured = BASE.length > 0 && PASSWORD.length > 0;

const BASE64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/**
 * Encodes bytes as standard, padded base64.
 *
 * Stands in for what the native crypto module returns. Getting this wrong would
 * produce a challenge the portal rejects, which is precisely what this test is
 * here to notice.
 * @param bytes - The bytes to encode.
 * @returns The padded base64 string.
 */
function toBase64(bytes: Uint8Array): string {
  let encoded = '';
  for (let offset = 0; offset < bytes.length; offset += 3) {
    const remaining = bytes.length - offset;
    const word =
      (bytes[offset] << 16) |
      ((remaining > 1 ? bytes[offset + 1] : 0) << 8) |
      (remaining > 2 ? bytes[offset + 2] : 0);
    const chars = [
      BASE64[(word >> 18) & 63],
      BASE64[(word >> 12) & 63],
      remaining > 1 ? BASE64[(word >> 6) & 63] : '=',
      remaining > 2 ? BASE64[word & 63] : '=',
    ];
    encoded += chars.join('');
  }
  return encoded;
}

const mockBrowser = { redirectUrl: '', factors: '' };
const mockJar = new Map<string, string>();

/**
 * Stores every cookie a response sets.
 *
 * One response can set several, and reading the joined header keeps only the
 * first - which silently drops the session cookie the Google callback issues
 * alongside the one it clears.
 * @param res - The response to read.
 */
function rememberCookies(res: Response): void {
  const headers = res.headers as unknown as { getSetCookie?: () => string[] };
  for (const entry of headers.getSetCookie?.() ?? []) {
    const pair = entry.split(';')[0];
    const split = pair.indexOf('=');
    if (split > 0) {
      mockJar.set(pair.slice(0, split).trim(), pair.slice(split + 1));
    }
  }
}

/**
 * Issues a request carrying the collected cookies, the way a browser would.
 * @param url - Where to go.
 * @param init - Fetch options.
 * @returns The response, with any new cookies already stored.
 */
async function hop(url: string, init: RequestInit = {}): Promise<Response> {
  const headers = { ...(init.headers as Record<string, string> | undefined) };
  if (mockJar.size > 0) {
    headers.cookie = [...mockJar].map(([name, value]) => `${name}=${value}`).join('; ');
  }
  const res = await fetch(url, { ...init, headers, redirect: 'manual' });
  rememberCookies(res);
  return res;
}

/**
 * Produces random bytes the way the native module would.
 * @param byteCount - How many bytes to produce.
 * @returns The generated bytes.
 */
function mockRandomBytes(byteCount: number): Uint8Array {
  return globalThis.crypto.getRandomValues(new Uint8Array(byteCount));
}

/**
 * Hashes a string with SHA-256 and returns standard base64.
 * @param data - The value to hash.
 * @returns The padded base64 digest.
 */
async function mockDigestBase64(data: string): Promise<string> {
  const input = new TextEncoder().encode(data);
  const hashed = await globalThis.crypto.subtle.digest('SHA-256', input);
  return toBase64(new Uint8Array(hashed));
}

jest.mock('expo-crypto', () => ({
  CryptoDigestAlgorithm: { SHA256: 'SHA-256' },
  CryptoEncoding: { BASE64: 'base64' },
  getRandomBytesAsync: (byteCount: number) => Promise.resolve(mockRandomBytes(byteCount)),
  digestStringAsync: (_algorithm: string, data: string) => mockDigestBase64(data),
}));

jest.mock('expo-device', () => ({ deviceName: 'Live test device' }));

jest.mock('expo-linking', () => ({
  parse: (url: string) => {
    const query = url.includes('?') ? url.slice(url.indexOf('?') + 1) : '';
    const queryParams: Record<string, string> = {};
    for (const [key, value] of new URLSearchParams(query)) {
      queryParams[key] = value;
    }
    return { queryParams };
  },
}));

jest.mock('expo-web-browser', () => ({
  WebBrowserResultType: { CANCEL: 'cancel', DISMISS: 'dismiss', LOCKED: 'locked' },
  openAuthSessionAsync: (url: string) => mockSignInThroughPortal(url),
}));

/**
 * Satisfies the Google factor through whatever identity provider the portal is
 * pointed at.
 *
 * The consent page is fetched and its approve link followed, which is all a
 * person does on that screen.
 */
async function satisfyGoogle(): Promise<void> {
  const start = await hop(`${BASE}/auth/google`);
  const consentUrl = start.headers.get('location') ?? '';
  if (!consentUrl) {
    throw new Error(`Portal did not redirect to an identity provider (${String(start.status)}).`);
  }
  const consent = await fetch(consentUrl);
  const page = await consent.text();
  const link = /href="([^"]+)"/.exec(page)?.[1];
  if (!link) {
    throw new Error('Consent page carried no approve link.');
  }
  const callback = await hop(link.replace(/&amp;/g, '&'));
  if (callback.status >= 400) {
    throw new Error(`Google callback rejected (${String(callback.status)}).`);
  }
}

/**
 * Satisfies the password factor.
 */
async function satisfyPassword(): Promise<void> {
  const login = await hop(`${BASE}/auth/login`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ password: PASSWORD }),
  });
  if (!login.ok) {
    throw new Error(`Portal login failed (${String(login.status)}).`);
  }
}

/**
 * Signs in to the portal over HTTP and follows the authorize redirect.
 *
 * This stands in for the system browser: it satisfies whatever factors the
 * portal currently demands, then replays the authorize request the app built,
 * unchanged.
 * @param authorizeUrl - The authorization URL the app produced.
 * @returns A browser-shaped result carrying the redirect.
 */
async function mockSignInThroughPortal(
  authorizeUrl: string,
): Promise<{ type: string; url?: string }> {
  mockJar.clear();
  const status = (await (await fetch(`${BASE}/auth/status`)).json()) as { authMode?: string };
  if (status.authMode === 'google' || status.authMode === 'both') {
    await satisfyGoogle();
  }
  if (status.authMode === 'password' || status.authMode === 'both') {
    await satisfyPassword();
  }

  const settled = (await (await hop(`${BASE}/auth/status`)).json()) as {
    google?: boolean;
    password?: boolean;
  };
  mockBrowser.factors = `google=${String(settled.google)} password=${String(settled.password)}`;

  const authorized = await hop(authorizeUrl);
  const location = authorized.headers.get('location') ?? '';
  mockBrowser.redirectUrl = location;
  return location.startsWith('bankimporter://')
    ? { type: 'success', url: location }
    : { type: 'locked' };
}

const describeLive = isConfigured ? describe : describe.skip;

describeLive('app sign-in against a live portal', () => {
  it('completes the flow and returns a usable access token', async () => {
    const tokens = await signIn(BASE);

    expect(mockBrowser.factors).toBe('google=true password=true');
    expect(mockBrowser.redirectUrl.startsWith('bankimporter://auth?')).toBe(true);
    expect(tokens.accessToken.length).toBeGreaterThan(0);
    expect(tokens.refreshToken.length).toBeGreaterThan(0);
    expect(tokens.expiresAt).toBeGreaterThan(Date.now());

    const guarded = await fetch(`${BASE}/api/status`, {
      headers: { authorization: `Bearer ${tokens.accessToken}` },
    });
    expect(guarded.status).toBe(200);
  }, 60_000);

  it('rotates the refresh token and keeps the session usable', async () => {
    const first = await signIn(BASE);
    const second = await refreshTokens(BASE, first.refreshToken);

    expect(second.refreshToken).not.toBe(first.refreshToken);

    const guarded = await fetch(`${BASE}/api/status`, {
      headers: { authorization: `Bearer ${second.accessToken}` },
    });
    expect(guarded.status).toBe(200);
  }, 60_000);

  it('refuses a refresh token that has already been spent', async () => {
    const first = await signIn(BASE);
    await refreshTokens(BASE, first.refreshToken);

    await expect(refreshTokens(BASE, first.refreshToken)).rejects.toThrow(SESSION_ENDED);
  }, 60_000);

  it('stops working once the device is revoked from the portal', async () => {
    const tokens = await signIn(BASE);
    const sessions = (await (
      await fetch(`${BASE}/api/app/sessions`, {
        headers: { authorization: `Bearer ${tokens.accessToken}` },
      })
    ).json()) as { id: string; current: boolean }[];
    const current = sessions.find((entry) => entry.current);
    expect(current).toBeDefined();

    const revoked = await fetch(`${BASE}/api/app/sessions/${String(current?.id)}`, {
      method: 'DELETE',
      headers: { authorization: `Bearer ${tokens.accessToken}` },
    });
    expect(revoked.status).toBe(200);

    await expect(refreshTokens(BASE, tokens.refreshToken)).rejects.toThrow(SESSION_ENDED);
  }, 60_000);
});
