/**
 * Proves the PKCE material the app sends is what an authorization server will
 * accept.
 *
 * The correctness anchor is the RFC 7636 Appendix B test vector: feeding its
 * exact octets must reproduce its published verifier, and its published digest
 * must convert to its published challenge. That checks this module against the
 * specification rather than against a second copy of the same arithmetic.
 *
 * `expo-crypto` is a native module, so it is replaced by a stub that records
 * what it was asked to hash. What matters here is that the challenge is derived
 * from the verifier itself, with SHA-256 and base64 output — not that the
 * platform's SHA-256 works, which no unit test can establish.
 */
import { createPkcePair, createState } from './pkce';

/** RFC 7636 Appendix B: the octets behind the published verifier. */
const RFC_VERIFIER_BYTES = new Uint8Array([
  116, 24, 223, 180, 151, 153, 224, 37, 79, 250, 96, 125, 216, 173, 187, 186, 22, 212, 37, 77, 105,
  214, 191, 240, 91, 88, 5, 88, 83, 132, 141, 121,
]);

/** RFC 7636 Appendix B: the verifier those octets encode to. */
const RFC_VERIFIER = 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk';

/** RFC 7636 Appendix B: SHA-256 of the verifier, in standard base64. */
const RFC_DIGEST_BASE64 = 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw+cM=';

/** RFC 7636 Appendix B: the challenge that digest must produce. */
const RFC_CHALLENGE = 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM';

const BASE64URL = /^[\w-]+$/;

const mockCrypto = {
  bytes: [] as Uint8Array[],
  digest: RFC_DIGEST_BASE64,
  digestCalls: [] as { algorithm: string; data: string; encoding: string }[],
};

jest.mock('expo-crypto', () => ({
  CryptoDigestAlgorithm: { SHA256: 'SHA-256' },
  CryptoEncoding: { BASE64: 'base64' },
  getRandomBytesAsync: (byteCount: number) =>
    Promise.resolve(mockCrypto.bytes.shift() ?? new Uint8Array(byteCount)),
  digestStringAsync: (algorithm: string, data: string, options: { encoding: string }) => {
    mockCrypto.digestCalls.push({ algorithm, data, encoding: options.encoding });
    return Promise.resolve(mockCrypto.digest);
  },
}));

/**
 * Builds deterministic, non-zero bytes so two calls can be told apart.
 * @param byteCount - How many bytes to produce.
 * @param seed - Offset applied to every byte.
 * @returns The generated bytes.
 */
function bytesFrom(byteCount: number, seed: number): Uint8Array {
  const values = Array.from({ length: byteCount }, (_unused, index) => (index * 7 + seed) % 256);
  return new Uint8Array(values);
}

beforeEach(() => {
  mockCrypto.bytes = [];
  mockCrypto.digest = RFC_DIGEST_BASE64;
  mockCrypto.digestCalls = [];
});

describe('createPkcePair', () => {
  it('reproduces the RFC 7636 verifier from its published octets', async () => {
    mockCrypto.bytes = [RFC_VERIFIER_BYTES];
    const { verifier } = await createPkcePair();
    expect(verifier).toBe(RFC_VERIFIER);
  });

  it('reproduces the RFC 7636 challenge from its published digest', async () => {
    mockCrypto.bytes = [RFC_VERIFIER_BYTES];
    const { challenge } = await createPkcePair();
    expect(challenge).toBe(RFC_CHALLENGE);
  });

  it('hashes the verifier itself, with SHA-256 and base64 output', async () => {
    mockCrypto.bytes = [RFC_VERIFIER_BYTES];
    const { verifier } = await createPkcePair();
    expect(mockCrypto.digestCalls).toEqual([
      { algorithm: 'SHA-256', data: verifier, encoding: 'base64' },
    ]);
  });

  it('rewrites both base64 characters that are illegal in a URL', async () => {
    mockCrypto.digest = 'ab+cd/ef+gh/ij==';
    const { challenge } = await createPkcePair();
    expect(challenge).toBe('ab-cd_ef-gh_ij');
  });

  it('produces a 43-character verifier in the base64url alphabet', async () => {
    mockCrypto.bytes = [bytesFrom(32, 3)];
    const { verifier } = await createPkcePair();
    expect(verifier).toHaveLength(43);
    expect(verifier).toMatch(BASE64URL);
  });

  it('never emits base64 padding or the two non-url characters', async () => {
    mockCrypto.bytes = [bytesFrom(32, 11)];
    const { verifier, challenge } = await createPkcePair();
    expect(`${verifier}${challenge}`).not.toMatch(/[+/=]/);
  });

  it('returns a different verifier when the entropy differs', async () => {
    mockCrypto.bytes = [bytesFrom(32, 1), bytesFrom(32, 2)];
    const first = await createPkcePair();
    const second = await createPkcePair();
    expect(first.verifier).not.toBe(second.verifier);
  });
});

describe('createState', () => {
  it('produces a 22-character value in the base64url alphabet', async () => {
    mockCrypto.bytes = [bytesFrom(16, 5)];
    const state = await createState();
    expect(state).toHaveLength(22);
    expect(state).toMatch(BASE64URL);
  });

  it('returns a different value when the entropy differs', async () => {
    mockCrypto.bytes = [bytesFrom(16, 1), bytesFrom(16, 2)];
    const first = await createState();
    const second = await createState();
    expect(first).not.toBe(second);
  });
});
